### ISSUE TITLE
Merge to Main necessario e clean up consigliabile

### ISSUE THREAD

**Issue by EbekSynthsei** [FabioFlo/ProjectWork#12]
Al momento il progetto può fermarsi non essendo più prevista una consegna, tuttavia appena possibile cercherò di effettuare un merge sul _main_ del branch _TestThyme_, così da avere meno "confusione" e poterlo presentare più efficacemente, cercherò di occuparmene personalmente.

Aggiungerei un _ReadMe_ sul come utilizzare questa repository, per rendere l'uso del progetto più accessibile e comprensibile per chi non abbia seguito il suo sviluppo, ma personalmente non sono bravo a fare le guide.

Molti dei file in realtà non dovrebbero essere necessari, mi riferisco in particolare alla sezione DTO.
@FabioFlo 
Dovrebbe essere possibile ricondurre le _Repository JPA_ ad appoggiarsi comunque al _Service_, così da mantenere la separazione dei vari layer di interazione con il _DB_. Se e quando avrai tempo libero ti chiedo di fare dei test a riguardo, avendo integrato per primo quella sezione. Io sto continuando a vedere come rendere effettivo il salvataggio _ManyToMany._

@AlisaMorpheus e @macco14 
Dato il lavorone che avete fatto in due giorni per renderlo visivamente accettabile e data l'esperienza fatta con _Thymeleaf_, _HTML_ e _CSS_, continuerei a lavorare su quegli aspetti (sempre se e quando fosse possibile).

@MrBabaMa
Dato che non hai avuto modo di seguire alcune parti, provvederei a commentare il codice così che sia comprensibile per tutti i futuri lettori.

Infine, inviterei i compagni del corso a integrare i due progetti GaMeet e questo, espandendo la repo e affinandone i vari aspetti, ma di questo ne possiamo discutere in un'altro momento.
Nel frattempo, complimenti a noi.

**Comment by EbekSynthsei** [comment]
Ok il merge sul main non sembra aver dato problemi, rimarrei con gli altri elementi aperti su questo Issue così da non aprirne altri.
Let me know!

**Comment by macco14** [comment]
Perfetto, quando ho tempo posso continuare la parte grafica. Sono d'accordissimo per sentire  il gruppo di GaMeet, i loro progetto è davvero interessante. Per quanto riguarda il ReadMe ho visto che deve essere scritto con metodi particolar, mi leggo qualche guida

**Comment by EbekSynthsei** [comment]
ORA FUNZIONA
